---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: n8n-secret
  namespace: n8n
spec:
  encryptedData:
    N8N_ENCRYPTION_KEY: AgDs2UqpASQdMliXx0ijHENkxY0Vge0JnCxYwo3WAIx9wYvuoavH8jDCLG6GcCNWFNMfSFSv1R4ZbQSHdKhnuq9SYk8w/ZrjpzGpAd/8jljBwDOf6XKkgtb38qiOAoYwK1dsrWN0lsMbjperbq28fNqYyABBYsm8RVCGL5PN2AGrx/jx/QIsRd/uwIAzNCyWTfXfssgkr3blwzvf6HGtor3IcA2VZduigsAHe3m3kxQLk/SimI3HCZb2k7zsiEuDoorhGn0YJEDeJRroeK1A4XHS/9K+Z9EPcAO1HpdElxHS5/2Yu9sgDKfFp7Nebqh9ZUaJm0qtUqYAHIfVtl6UCf/EAUY1/vSpi5lp7BcFj1sTJ55KVv3+MS13/m0P2gtryj8ofqXt4U4Pd4KSASffR05iodVoLrpfv325E8UQNj25okUioUL/2iUqhP7Kemw5p+CUdMCWLy1F2DfZQbfU4e7wKEcPcPKpLiJomiR+jIgvJAMY4ES/0neLnX1rdhS3ictVDwdJ7N+YWDv/eB3WKKh10Bz3mNdCSkuElsrHXCl/0MErmGi2EIupiL60CNqnWpVCbinZYvDptMaiW7h7A7ofDaJYs0ITd0s2z3cR17QbzWG1Rp+pa/Q8Ii36N3CfPEZxaC6F/YUbT5+wRru9SRzSThRhEw4DkXxDJ7gtO+HO5nl5RV0tFPNWaIli0zl8/SSBwNEyR6b2wmChmQucQLxfxv9ufh4tFL1CdEjmj938vOiYTcUrbTlSJzbsaSst6vI=
  template:
    metadata:
      name: n8n-secret
      namespace: n8n
