apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: strimzi-kafka-operator
  namespace: operator-kafka
spec:
  selector:
    matchLabels:
      name: strimzi-cluster-operator
  podMetricsEndpoints:
    - port: http
      path: /metrics
